### ISSUE TITLE
D10 L178 CP/FT 排程新增需求

### ISSUE THREAD

**Issue by Colara** [Sigurd-Hukou/CredenceD10-OI#72]
將客戶程式所產生出來的filelog(.txt & .csv)壓成.gz後回傳給客戶
因為客戶filelog是邊測邊存，為了避免壓縮到未測完的檔案，請抓檔名時間後8小時再壓縮檔案。

FT 路徑  /usr/local/home/vol5/RealTimelog/L178/Temp_FT  壓縮完後搬到 /usr/local/home/vol5/RealTimelog/L178/FT  檔案最後一欄位是 Default 不需壓縮。
CP 路徑 /usr/local/home/vol5/RealTimelog/L178/Temp_CP  壓縮完後搬到 /usr/local/home/vol5/RealTimelog/L178/CP  檔案最後一欄位是 Default 不需壓縮。

**Comment by whooes** [comment]
檔案執行超過八小時，資料壓縮覆蓋問題。將嘗試以mv --backup=t  不會被覆蓋並加上流水號解決。

**Comment by whooes** [comment]
java_Regular_Expression.csh 加入backup，未來搬動相同檔名不會被覆蓋並加上流水號(ex: ~1~)

**Comment by whooes** [comment]
時間需求更改為超過24小時。

**Comment by whooes** [comment]
CP功能完成待上線。

**Comment by whooes** [comment]
修正時間判斷例外case。
