### ISSUE TITLE
L401 RE  STDF & XML 填入資訊確認

### ISSUE THREAD

**Issue by whooes** [Sigurd-Hukou/CredenceD10-OI#78]
[RE  STDF & XML 填入資訊確認　- SIGURD.zip](https://github.com/Sigurd-Hukou/CredenceD10-OI/files/5139587/RE.STDF.XML.-.SIGURD.zip)

A. 是否有填入以下資訊到FT的STDF file
包含MIR底下的RTST_COD欄位應填入RT次數，以及TST_TEMP應該填入「實際」handler的測試溫度
※須注意：拆批續測的也要延續，不可以又變成First test
For example，下列MIR代表這筆貨的第3次壞品重測，且測試溫度是85C:
MIR:K61GJH1|RTL1234BND-VBA-CG|RT1234BND-VBA_V08.xls|J750-55|J750|06:26:38 21-Jul-2020|07:13:54 21-Jul-2020|103P329||0|||3||IG-XL|3.50.40 (P1403)||||85|RTL1234BND-VBA_V08||MQFNT48C||K27

frmMain.DataCollection1.LotSetup.TstTemp = Temperature_N ------原本已有

全部都給，給定位置選擇(之前全給，之後else其餘各戶分別加入)
frmMain.DataCollection1.LotSetup.RetestCode = Mid(setRetestNumber, 2) ------------待加入
L401 & F199

**Comment by Colara** [comment]
客戶通知需加入新欄位至MIR , D10共需修改以下四個欄位 , 於SD10-01 , SD10-10 Try Run

**MODE_COD** -> D10系統限制無法帶入 改由Tango後製，750帶入固定字 ”P”
**TEST_COD**   -> 帶入站點
**USER_TXT**    -> 帶入Barcode 程式名稱
**Retest_COD** -> 帶入重測次數


[RE  STDF & XML 填入資訊確認　- SIGURD.zip](https://github.com/Sigurd-Hukou/CredenceD10-OI/files/5181911/RE.STDF.XML.-.SIGURD.zip)
